# render.yaml
services:
  - type: web
    name: your-telegram-bot  # 서비스 이름
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: INTERNAL_API_KEY
        sync: false
