services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd /opt/render/project/src && python modules/server.py" # <<< This is the critical change
    envVars:
      - key: PORT
        value: 10000
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false